class_path: superhuge.model.interface.MInterface
init_args:
  model_class: superhuge.model.former.Deformer_ws
  model_args:
    window_length: 10
    fs: 128
    num_kernels: 32
    temporal_kernel_size: 13
    mha_depth: 4
    mha_num_heads: 8
    mha_dim_heads: 160
    time_dim: 1280
    mha_embed_dim: 1280
    ff_hidden_dim: 128
    num_electrodes: 70
    dp_rate: .5
